# Generated by Django 4.1.7 on 2023-02-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_plans', '0002_alter_eventplan_short_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventplan',
            name='caption_image',
            field=models.ImageField(upload_to='event_image'),
        ),
    ]
